

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER menulist IDENTIFIED BY 1234;

GRANT CONNECT, CREATE SESSION, CREATE TABLE TO menulist;

ALTER USER menulist DEFAULT TABLESPACE
SYSTEM QUOTA UNLIMITED ON SYSTEM;

