
CREATE TABLE MENULIST (
	메뉴 VARCHAR2(50) PRIMARY KEY,
	가격 NUMBER  NOT NULL
);

INSERT INTO MENULIST VALUES(
	'후라이드 치킨', 16000
);

INSERT INTO MENULIST VALUES(
	'양념 치킨', 17000
);

INSERT INTO MENULIST VALUES(
	'간장 치킨', 17000
);

INSERT INTO MENULIST VALUES(
	'반반 치킨(메뉴 선택 가능)', 17000
	
INSERT INTO MENULIST VALUES(
	'치즈볼(4개)', 4000	

INSERT INTO MENULIST VALUES(
	'음료수', 3000	
);


UPDATE MENULIST SET 메뉴 = '탄산음료'
WHERE 메뉴 = '음료수';

SELECT * FROM MENULIST;

ALTER TABLE MENULIST ADD(원산지 VARCHAR2(20) DEFAULT '국내산');


COMMENT ON COLUMN MENULIST.메뉴 IS '메뉴명';
COMMENT ON COLUMN MENULIST.가격 IS '원화';
COMMENT ON COLUMN MENULIST.원산지 IS '원산지';



-- 메뉴와 가격 추가
INSERT INTO MENULIST VALUES(
	'메뉴명', 0000
);

-- 메뉴 수정
UPDATE MENULIST SET 메뉴 = '바꿀 메뉴명'
WHERE 메뉴 = '현재 메뉴명'

-- 가격 수정
UPDATE MENULIST SET 가격 = 0000 -- 바꿀 가격
WHERE 가격 = 0000 -- 현재 가격

-- 메뉴 삭제
DELETE FROM MENULIST WHERE 메뉴 = '삭제할 메뉴명';


SELECT 메뉴, 가격 || '원' 가격, 원산지
FROM MENULIST ;

COMMIT;

CREATE OR REPLACE VIEW MENU_VIEW 
AS SELECT * FROM MENULIST
WITH READ ONLY;

SELECT * FROM MENU_VIEW;
